adds Hermosillo chapter to config.yml and a static page
pyladies/pyladies pull request #539
Opened 2020-09-28 01:56 UTC by FernandaDguez

# PyLadies Pull Request
_Please document the following. We will aim to be as timely as possible in processing your pull request, however as this is a volunteer staffed project anticipate at least a week for pull requests to start to be reviewed._ 

## Is this pull requesting adding or updating a [PyLadies chapter information](https://github.com/pyladies/pyladies#to-add-a-new-pyladies-location)? 

- [x] Yes
- [ ] No

### :warning::warning: If you marked yes, please close this pull request and head over to the [PyLadies Chapter Websites repo](github.com/pyladies/chapter-websites#README.md) to add your website. Additionally, you should remove your website code from this repository! :warning::warning:

## Have you confirmed the website builds locally? See [here](https://github.com/pyladies/pyladies#run-the-site-locally).

- [x] Yes
- [ ] No

##  Does your pull request pass the `netlify/pyladies/deploy-preview` check?

- [ ] Yes
- [ ] No

# Pull Request Checklist

- [ ] Fill out all sections above
- [ ] Share pull request in PyLadies Slack channel #project-tech-infra

/cc @pyladies/tech-and-infra-admins

2020-10-01 16:15 UTC, lorenanicole requested changes
@FernandaDguez a few things:

1. Please remove the index.html page, we no longer are hosting PyLadies location pages on pyladies.com. Instead you must open a pull request to create your official PyLadies website here: https://github.com/pyladies/chapter-websites/issues before we will add to the official website location. There we can setup your custom domain, which will be the link you use in the www/config.yml file under website
2. Register your PyLadies chapter in the Chapter Directory here. You must be logged in with your PyLadies google account to access the form.
3. Once the above is complete, we will review this pull request again.

2020-10-01 16:15 UTC, lorenanicole commented on www/config.yml
> +  website: hermosillo
This is incorrect, please read comment in the pull request for how to remedy this.

2020-10-01 16:17 UTC, lorenanicole requested changes

2020-10-01 16:17 UTC, lorenanicole commented on www/locations/hermosillo/index.html
> +{% extends "site.html" %}
Remove this file completely. Instead the `website` will point to your custom domain. For an example see: https://github.com/pyladies/pyladies/blob/98e45e86635d4fb982b662d91eec7e904ab113f7/www/config.yml#L279.

2020-10-09 03:26 UTC, lorenanicole commented
@FernandaDguez you can now add this to your file - https://github.com/pyladies/pyladies/blob/98da2348ef545ffb1b4e5c5b68e26945678f384b/www/config.yml#L397 - and link to your chapter's website - https://hermosillo.pyladies.com!

2020-11-17 01:36 UTC, FernandaDguez commented
Hello, is there something else needed to merge this?

2021-01-13 17:25 UTC, Mariatta approved these changes
Thanks. Sorry for the delay.

2021-01-13 17:25 UTC, merged